# Generated by Django 5.2.4 on 2025-07-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moneyrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyRequest',
        ),
    ]
